name: A workflow for my Hello World file

on: push

jobs:

  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        marker: ["\"some marker\"", "\"another marker\"", "\"yet another marker\""]
    steps:
      - name: Echo name
        run: |
          echo "You are running with marker: ${{ matrix.marker }}."
